### ISSUE TITLE
Question regarding 2nd graph

### ISSUE THREAD

**Issue by htcml** [shitoushan/mixtureSPRT#1]
In https://github.com/shitoushan/mixtureSPRT graph 2, the null hypothesis is rejected after 307 observations. However, its ratio go below 20 afterwards and again after around 850 observations, so is it reliable to reject the null hypothesis at 307th observation?

**Comment by erik-giertz** [comment]
Hi! yes, the likelihood ratio is a martingale, and has no "memory" of past values. The LR has a certain probability of *ever* crossing the rejection-limit, which is how we bound type-I error rate to alpha.
